/*
 * JS for home generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '4115eca7-49e2-4c56-a360-c776f4ad3f81';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "ledger",
    "location": "#ledger"
}, {
    "name": "home",
    "location": "#home"
}];

function home_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'screen_nav': 'home_screen_nav',
        'new_nav': 'home_new_nav',
        'ledger_nav': 'home_ledger_nav',
        'balance': 'home_balance',
        'for': 'home_for',
        'amount': 'home_amount',
        'choose_action': 'home_choose_action',
        'choose_action-0': 'home_choose_action-0',
        'enter': 'home_enter',
        'account_nav': 'home_account_nav',
        'jax_nav': 'home_jax_nav',
        'remi_nav': 'home_remi_nav'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'home';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var home_onLoad = function() {
            home_elementsExtraJS();

            home_deviceEvents();
            home_windowEvents();
            home_elementsEvents();
        };

    // screen window events


    function home_windowEvents() {

        $('#home').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function home_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function home_elementsExtraJS() {
        // screen (home) extra code

        /* choose_action */

        $("#home_choose_action").parent().find("a.ui-btn").attr("tabindex", "2");

    };

    // screen elements handler


    function home_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#home_mobileheader [name="new_nav"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('home', {
                        reverse: false
                    });

                }
            },
        }, '#home_mobileheader [name="new_nav"]');
        $(document).off("click", '#home_mobileheader [name="ledger_nav"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('ledger', {
                        transition: 'fade',
                        reverse: false
                    });

                }
            },
        }, '#home_mobileheader [name="ledger_nav"]');

    };

    $(document).off("pagebeforeshow", "#home").on("pagebeforeshow", "#home", function(event, ui) {
        Apperyio.CurrentScreen = "home";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    home_onLoad();
};

$(document).off("pagecreate", "#home").on("pagecreate", "#home", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    home_js();
});

function ledger_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'screen_nav': 'ledger_screen_nav',
        'new_nav': 'ledger_new_nav',
        'ledger_nav': 'ledger_ledger_nav',
        'balance': 'ledger_balance',
        'tx_list': 'ledger_tx_list',
        'mobilelistitem_18': 'ledger_mobilelistitem_18',
        'mobilelistitembutton_19': 'ledger_mobilelistitembutton_19',
        'account_nav': 'ledger_account_nav',
        'jax_nav': 'ledger_jax_nav',
        'remi_nav': 'ledger_remi_nav'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'ledger';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var ledger_onLoad = function() {
            ledger_elementsExtraJS();

            ledger_deviceEvents();
            ledger_windowEvents();
            ledger_elementsEvents();
        };

    // screen window events


    function ledger_windowEvents() {

        $('#ledger').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function ledger_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function ledger_elementsExtraJS() {
        // screen (ledger) extra code

        /* tx_list */

        listView = $("#ledger_tx_list");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#ledger_tx_list .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_18 */

    };

    // screen elements handler


    function ledger_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#ledger_mobileheader [name="new_nav"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('home', {
                        transition: 'fade',
                        reverse: true
                    });

                }
            },
        }, '#ledger_mobileheader [name="new_nav"]');
        $(document).off("click", '#ledger_mobileheader [name="ledger_nav"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('ledger', {
                        reverse: false
                    });

                }
            },
        }, '#ledger_mobileheader [name="ledger_nav"]');

    };

    $(document).off("pagebeforeshow", "#ledger").on("pagebeforeshow", "#ledger", function(event, ui) {
        Apperyio.CurrentScreen = "ledger";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    ledger_onLoad();
};

$(document).off("pagecreate", "#ledger").on("pagecreate", "#ledger", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    ledger_js();
});